# Generated by Django 6.0.1 on 2026-04-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion_corta', models.CharField(blank=True, max_length=255)),
                ('icono', models.CharField(blank=True, max_length=64)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('foto', models.ImageField(blank=True, upload_to='especialistas/')),
                ('cedula_profesional', models.CharField(max_length=20)),
                ('cedula_especialidad', models.CharField(blank=True, max_length=20)),
                ('cmcper', models.CharField(blank=True, max_length=20)),
                ('biografia', models.TextField()),
                ('universidad', models.CharField(blank=True, max_length=200)),
                ('hospital_especialidad', models.CharField(blank=True, max_length=200)),
                ('anios_experiencia', models.PositiveIntegerField(blank=True, null=True)),
                ('areas_interes', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('publicado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('especialidades', models.ManyToManyField(blank=True, related_name='especialistas', to='especialistas.especialidad')),
            ],
            options={
                'verbose_name_plural': 'Especialistas',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
